version: '3.8'
services:

  web:
    build: ./python
    ports:
      - "8000:8000"
    depends_on:
      - db
      
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=patients
    ports:
    - '5438:5432'
    volumes:
      - ./python/persistence/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - maverick_postgres:/var/lib/postgresql/data



volumes:
  maverick_postgres:
    driver: local


